import "./globals.css";
import Link from "next/link";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  ogImage: "https://example.com/og-image.jpg", // Replace with your actual OG image URL
  ogUrl: "https://example.com", // Replace with your actual URL
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />

        {/* Open Graph meta tags */}
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content={metadata.ogImage} />
        <meta property="og:url" content={metadata.ogUrl} />
        <meta property="og:type" content="website" />

        {/* Twitter meta tags (optional) */}
        <meta name="twitter:card" content="summary_large_image" />
        {/* Add more Twitter meta tags if needed */}

        {/* Favicon link (replace with your actual favicon path) */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="flex justify-between bg-black text-white py-5 font-semibold ">
          <div className="ml-5 text-lg font-bold">
            <Link href={"/"}>
              <span className="text-red-300">My</span>{" "}
              <span className="text-yellow-500">Portfolio</span>
            </Link>
          </div>
          <div className="flex justify-center align-center">
            <Link href="/" className="mr-5 link">
              Home
            </Link>
            <Link href="/about" className="mr-5 link">
              About
            </Link>
            <Link href="/skills" className="mr-5 link">
              Skills
            </Link>
            <Link href="/contact" className="mr-5 link">
              Contact
            </Link>
            <Link href="/project" className="mr-5 link">
              Project
            </Link>
          </div>
          <div className="mr-5 bg-white text-black px-3 py-1 rounded">
            <Link href={"/contact"}>Contact</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
